schema_version = "1.0.0"

id = "reclaimer_rmf_importer"
version = "1.0.5"
name = "RMF format"
tagline = "Import RMF files created by Reclaimer"
maintainer = "Gravemind2401"
type = "add-on"

website = "https://github.com/Gravemind2401/Reclaimer"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "windows-arm64", "linux-x64", "macos-arm64", "macos-x64"]
# Supported platforms: "windows-arm64", "windows-x64", "linux-x64", "macos-arm64", "macos-x64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/pyside6-6.11.1-cp310-abi3-macosx_13_0_universal2.whl",
  "./wheels/pyside6-6.11.1-cp310-abi3-manylinux_2_34_x86_64.whl",
  "./wheels/pyside6-6.11.1-cp310-abi3-win_amd64.whl",
  "./wheels/pyside6-6.11.1-cp310-abi3-win_arm64.whl",
  "./wheels/pyside6_addons-6.11.1-cp310-abi3-macosx_13_0_universal2.whl",
  "./wheels/pyside6_addons-6.11.1-cp310-abi3-manylinux_2_34_x86_64.whl",
  "./wheels/pyside6_addons-6.11.1-cp310-abi3-win_amd64.whl",
  "./wheels/pyside6_addons-6.11.1-cp310-abi3-win_arm64.whl",
  "./wheels/pyside6_essentials-6.11.1-cp310-abi3-macosx_13_0_universal2.whl",
  "./wheels/pyside6_essentials-6.11.1-cp310-abi3-manylinux_2_34_x86_64.whl",
  "./wheels/pyside6_essentials-6.11.1-cp310-abi3-win_amd64.whl",
  "./wheels/pyside6_essentials-6.11.1-cp310-abi3-win_arm64.whl",
  "./wheels/shiboken6-6.11.1-cp310-abi3-macosx_13_0_universal2.whl",
  "./wheels/shiboken6-6.11.1-cp310-abi3-manylinux_2_34_x86_64.whl",
  "./wheels/shiboken6-6.11.1-cp310-abi3-win_amd64.whl",
  "./wheels/shiboken6-6.11.1-cp310-abi3-win_arm64.whl",

  # blender doesnt natively support the macosx _universal2 tag yet so we need to duplicate and rename the wheels to _x86_64 and _arm64
  "./wheels/pyside6-6.11.1-cp310-abi3-macosx_13_0_x86_64.whl",
  "./wheels/pyside6_addons-6.11.1-cp310-abi3-macosx_13_0_x86_64.whl",
  "./wheels/pyside6_essentials-6.11.1-cp310-abi3-macosx_13_0_x86_64.whl",
  "./wheels/shiboken6-6.11.1-cp310-abi3-macosx_13_0_x86_64.whl",
  "./wheels/pyside6-6.11.1-cp310-abi3-macosx_13_0_arm64.whl",
  "./wheels/pyside6_addons-6.11.1-cp310-abi3-macosx_13_0_arm64.whl",
  "./wheels/pyside6_essentials-6.11.1-cp310-abi3-macosx_13_0_arm64.whl",
  "./wheels/shiboken6-6.11.1-cp310-abi3-macosx_13_0_arm64.whl",
]

[permissions]
files = "Import RMF files from disk"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "autodesk/",
  "tests/",
  "import_rmf.py",
]