//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclaimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reclaimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;fieldDefinitions&gt;
        ///    &lt;revisions size=&quot;0&quot; valueType=&quot;revisions&quot; /&gt;
        ///
        ///    &lt;structure size=&quot;12&quot; valueType=&quot;structure&quot;&gt;
        ///        &lt;alias name=&quot;struct&quot; /&gt;
        ///        &lt;alias name=&quot;reflexive&quot; /&gt;
        ///        &lt;alias name=&quot;tagBlock&quot; /&gt;
        ///    &lt;/structure&gt;
        ///
        ///    &lt;tagReference size=&quot;16&quot; valueType=&quot;tagReference&quot;&gt;
        ///        &lt;alias name=&quot;tagRef&quot; /&gt;
        ///    &lt;/tagReference&gt;
        ///
        ///    &lt;stringId size=&quot;4&quot; valueType=&quot;stringId&quot; /&gt;
        ///
        ///    &lt;string size=&quot;length&quot; valueType=&quot;string&quot;&gt;
        ///        &lt;alias nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3FieldDefinitions {
            get {
                return ResourceManager.GetString("Halo3FieldDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;fieldDefinitions&gt;
        ///    &lt;_field_tag_reference_64 size=&quot;32&quot; valueType=&quot;tagReference&quot; /&gt;
        ///    &lt;_field_block_64 size=&quot;28&quot; valueType=&quot;structure&quot; /&gt;
        ///
        ///    &lt;_field_data_64 size=&quot;28&quot; valueType=&quot;&quot; hidden=&quot;true&quot; /&gt;
        ///    &lt;_field_pageable_resource_64 size=&quot;16&quot; valueType=&quot;&quot; hidden=&quot;true&quot; /&gt;
        ///    &lt;_field_tag size=&quot;4&quot; valueType=&quot;string&quot; hidden=&quot;true&quot; /&gt;
        ///
        ///    &lt;_field_struct size=&quot;sum&quot; valueType=&quot;array&quot; /&gt;
        ///    &lt;_field_array size=&quot;sum&quot; valueType=&quot;array&quot; /&gt;
        ///
        ///    &lt;_field_string_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo5FieldDefinitions {
            get {
                return ResourceManager.GetString("Halo5FieldDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;fieldDefinitions&gt;
        ///  &lt;_field_tag_reference_64 size=&quot;28&quot; valueType=&quot;tagReference&quot; /&gt;
        ///  &lt;_field_block_64 size=&quot;20&quot; valueType=&quot;structure&quot; /&gt;
        ///
        ///  &lt;_field_data_64 size=&quot;24&quot; valueType=&quot;padding&quot; hidden=&quot;true&quot; /&gt;
        ///  &lt;_field_pageable_resource_64 size=&quot;16&quot; valueType=&quot;&quot; hidden=&quot;true&quot; /&gt;
        ///  &lt;_field_tag size=&quot;4&quot; valueType=&quot;string&quot; hidden=&quot;true&quot; /&gt;
        ///
        ///  &lt;_field_struct size=&quot;sum&quot; valueType=&quot;array&quot; /&gt;
        ///  &lt;_field_array size=&quot;sum&quot; valueType=&quot;array&quot; /&gt;
        ///
        ///  &lt;_field_string_id size=&quot;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HaloInfiniteFieldDefinitions {
            get {
                return ResourceManager.GetString("HaloInfiniteFieldDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;HaloReach&quot;: {
        ///        &quot;Campaign&quot;: [
        ///            {
        ///                &quot;DisplayName&quot;: &quot;Noble Actual&quot;,
        ///                &quot;FileName&quot;: &quot;m05.map&quot;,
        ///                &quot;MccThumbnails&quot;: [
        ///                    &quot;HREACH_C01_NOBLEACTUAL&quot;,
        ///                    &quot;HREACH_C01_NOBLEACTUAL_LARGE&quot;
        ///                ]
        ///            },
        ///            {
        ///                &quot;DisplayName&quot;: &quot;Winter Contingency&quot;,
        ///                &quot;FileName&quot;: &quot;m10.map&quot;,
        ///                &quot;MccThumbnails&quot;: [
        ///                    &quot;HREACH_C02_WINTERCONTINGENC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapBrowserTemplates {
            get {
                return ResourceManager.GetString("MapBrowserTemplates", resourceCulture);
            }
        }
    }
}
