//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adjutant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adjutant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;classes&gt;
        ///  &lt;class code=&quot;actr&quot; name=&quot;actor&quot; /&gt;
        ///  &lt;class code=&quot;actv&quot; name=&quot;actor_variant&quot; /&gt;
        ///  &lt;class code=&quot;ant!&quot; name=&quot;antenna&quot; /&gt;
        ///  &lt;class code=&quot;antr&quot; name=&quot;model_animations&quot; /&gt;
        ///  &lt;class code=&quot;bipd&quot; name=&quot;biped&quot; /&gt;
        ///  &lt;class code=&quot;bitm&quot; name=&quot;bitmap&quot; /&gt;
        ///  &lt;class code=&quot;boom&quot; name=&quot;spheroid&quot; /&gt;
        ///  &lt;class code=&quot;cdmg&quot; name=&quot;continuous_damage_effect&quot; /&gt;
        ///  &lt;class code=&quot;coll&quot; name=&quot;model_collision_geometry&quot; /&gt;
        ///  &lt;class code=&quot;colo&quot; name=&quot;color_table&quot; /&gt;
        ///  &lt;class code=&quot;cont&quot; name=&quot;contrail&quot; /&gt;
        ///  &lt;class co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo1Classes {
            get {
                return ResourceManager.GetString("Halo1Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;classes&gt;
        ///  &lt;class code=&quot;*cen&quot; name=&quot;scenario_scenery_resource&quot; /&gt;
        ///  &lt;class code=&quot;*eap&quot; name=&quot;scenario_weapons_resource&quot; /&gt;
        ///  &lt;class code=&quot;*ehi&quot; name=&quot;scenario_vehicles_resource&quot; /&gt;
        ///  &lt;class code=&quot;*fsc&quot; name=&quot;scenario_effect_scenery_resource&quot; /&gt;
        ///  &lt;class code=&quot;*igh&quot; name=&quot;scenario_lights_resource&quot; /&gt;
        ///  &lt;class code=&quot;*ipd&quot; name=&quot;scenario_bipeds_resource&quot; /&gt;
        ///  &lt;class code=&quot;*qip&quot; name=&quot;scenario_equipment_resource&quot; /&gt;
        ///  &lt;class code=&quot;*rea&quot; name=&quot;scenario_creature_resource&quot; /&gt;
        ///  &lt;class code=&quot;*sce&quot; name=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo2Classes {
            get {
                return ResourceManager.GetString("Halo2Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;stringDefinitions&gt;
        ///  &lt;stringIDs id=&quot;beta&quot; indexBits=&quot;16&quot; namespaceBits=&quot;8&quot; lengthBits=&quot;8&quot;&gt;
        ///    &lt;namespace id=&quot;0x0&quot; min=&quot;0x4CD&quot; startIndex=&quot;0x962&quot; /&gt;
        ///    &lt;namespace id=&quot;0x1&quot; startIndex=&quot;0x4CD&quot; /&gt;
        ///    &lt;namespace id=&quot;0x2&quot; startIndex=&quot;0x85C&quot; /&gt;
        ///    &lt;namespace id=&quot;0x3&quot; startIndex=&quot;0x8B4&quot; /&gt;
        ///    &lt;namespace id=&quot;0x4&quot; startIndex=&quot;0x911&quot; /&gt;
        ///    &lt;namespace id=&quot;0x5&quot; startIndex=&quot;0x8DA&quot; /&gt;
        ///    &lt;namespace id=&quot;0x6&quot; startIndex=&quot;0x921&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3Strings {
            get {
                return ResourceManager.GetString("Halo3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;VertexDefinitions&gt;
        ///  &lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_3&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0xC&quot; type=&quot;Float32_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;DHenN3&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x18&quot; type=&quot;DHenN3&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3VertexBuffer {
            get {
                return ResourceManager.GetString("Halo3VertexBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;stringDefinitions&gt;
        ///  &lt;stringIDs id=&quot;beta&quot; indexBits=&quot;18&quot; namespaceBits=&quot;8&quot; lengthBits=&quot;6&quot;&gt;
        ///    &lt;namespace id=&quot;0x0&quot; min=&quot;0x5D1&quot; startIndex=&quot;0x1D02&quot; /&gt;
        ///    &lt;namespace id=&quot;0x1&quot; startIndex=&quot;0x5D1&quot; /&gt;
        ///    &lt;namespace id=&quot;0x2&quot; startIndex=&quot;0xDB9&quot; /&gt;
        ///    &lt;namespace id=&quot;0x3&quot; startIndex=&quot;0xEA0&quot; /&gt;
        ///    &lt;namespace id=&quot;0x4&quot; startIndex=&quot;0xF0A&quot; /&gt;
        ///    &lt;namespace id=&quot;0x5&quot; startIndex=&quot;0xFEE&quot; /&gt;
        ///    &lt;namespace id=&quot;0x6&quot; startIndex=&quot;0x101C&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo4Strings {
            get {
                return ResourceManager.GetString("Halo4Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;VertexDefinitions&gt;
        ///	&lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///		&lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_4&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///		&lt;value stream=&quot;0&quot; offset=&quot;0x10&quot; type=&quot;Float16_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///		&lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;DHenN3&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///		&lt;value stream=&quot;0&quot; offset=&quot;0x18&quot; type=&quot;DecN4&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///	&lt;/vertex&gt;
        ///	&lt;vertex type=&quot;0x01 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo4VertexBuffer {
            get {
                return ResourceManager.GetString("Halo4VertexBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;classes&gt;
        ///  &lt;class code=&quot;GobS&quot; name=&quot;gobo_setting&quot; /&gt;
        ///  &lt;class code=&quot;LMMg&quot; name=&quot;lightmap_model_globals&quot; /&gt;
        ///  &lt;class code=&quot;LigS&quot; name=&quot;lighting_settings&quot; /&gt;
        ///  &lt;class code=&quot;SDzs&quot; name=&quot;streamingzoneset&quot; /&gt;
        ///  &lt;class code=&quot;&amp;lt;fx&amp;gt;&quot; name=&quot;sound_effect_template&quot; /&gt;
        ///  &lt;class code=&quot;aTag&quot; name=&quot;AnyTag&quot; /&gt;
        ///  &lt;class code=&quot;aaap&quot; name=&quot;AmbientActionPointDefinitionTag&quot; /&gt;
        ///  &lt;class code=&quot;achi&quot; name=&quot;achievements&quot; /&gt;
        ///  &lt;class code=&quot;acme&quot; name=&quot;gestalt&quot; /&gt;
        ///  &lt;class code=&quot;adlg&quot; name=&quot;ai_dialogue_globals&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo5Classes {
            get {
                return ResourceManager.GetString("Halo5Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;VertexDefinitions&gt;
        ///  &lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_4&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x10&quot; type=&quot;Float16_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;DHenN3&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x18&quot; type=&quot;DecN4&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///  &lt;/vertex&gt;
        ///  &lt;vertex type=&quot;0x01&quot; name=&quot;s_rigid_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo5VertexBuffer {
            get {
                return ResourceManager.GetString("Halo5VertexBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;stringDefinitions&gt;
        ///  &lt;stringIDs id=&quot;beta&quot; indexBits=&quot;16&quot; namespaceBits=&quot;8&quot; lengthBits=&quot;8&quot;&gt;
        ///    &lt;namespace id=&quot;0x0&quot; min=&quot;0x464&quot; startIndex=&quot;0x13F3&quot; /&gt;
        ///    &lt;namespace id=&quot;0x1&quot; startIndex=&quot;0x464&quot; /&gt;
        ///    &lt;namespace id=&quot;0x2&quot; startIndex=&quot;0xA28&quot; /&gt;
        ///    &lt;namespace id=&quot;0x3&quot; startIndex=&quot;0xAD2&quot; /&gt;
        ///    &lt;namespace id=&quot;0x4&quot; startIndex=&quot;0xB37&quot; /&gt;
        ///    &lt;namespace id=&quot;0x5&quot; startIndex=&quot;0xC0C&quot; /&gt;
        ///    &lt;namespace id=&quot;0x6&quot; startIndex=&quot;0xC31&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HaloReachStrings {
            get {
                return ResourceManager.GetString("HaloReachStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;VertexDefinitions&gt;
        ///  &lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_4&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x10&quot; type=&quot;Float16_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;DHenN3&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x18&quot; type=&quot;DHenN3&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///  &lt;/vertex&gt;
        ///  &lt;verte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HaloReachVertexBuffer {
            get {
                return ResourceManager.GetString("HaloReachVertexBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;stringDefinitions&gt;
        ///  &lt;stringIDs id=&quot;U0&quot; indexBits=&quot;19&quot; namespaceBits=&quot;8&quot; lengthBits=&quot;5&quot;&gt;
        ///    &lt;namespace id=&quot;0x0&quot; min=&quot;0x633&quot; startIndex=&quot;0x210C&quot; /&gt;
        ///    &lt;namespace id=&quot;0x1&quot; startIndex=&quot;0x633&quot; /&gt;
        ///    &lt;namespace id=&quot;0x2&quot; startIndex=&quot;0xEC9&quot; /&gt;
        ///    &lt;namespace id=&quot;0x3&quot; startIndex=&quot;0xFD4&quot; /&gt;
        ///    &lt;namespace id=&quot;0x4&quot; startIndex=&quot;0x1061&quot; /&gt;
        ///    &lt;namespace id=&quot;0x5&quot; startIndex=&quot;0x1159&quot; /&gt;
        ///    &lt;namespace id=&quot;0x6&quot; startIndex=&quot;0x11A4&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHalo2XStrings {
            get {
                return ResourceManager.GetString("MccHalo2XStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;stringDefinitions&gt;
        ///  &lt;stringIDs id=&quot;U0&quot; indexBits=&quot;16&quot; namespaceBits=&quot;8&quot; lengthBits=&quot;8&quot;&gt;
        ///    &lt;namespace id=&quot;0x0&quot; min=&quot;0x4BB&quot; startIndex=&quot;0xCD3&quot; /&gt;
        ///    &lt;namespace id=&quot;0x1&quot; startIndex=&quot;0x4BB&quot; /&gt;
        ///    &lt;namespace id=&quot;0x2&quot; startIndex=&quot;0xAC1&quot; /&gt;
        ///    &lt;namespace id=&quot;0x3&quot; startIndex=&quot;0xB53&quot; /&gt;
        ///    &lt;namespace id=&quot;0x4&quot; startIndex=&quot;0xBA9&quot; /&gt;
        ///    &lt;namespace id=&quot;0x5&quot; startIndex=&quot;0xBBD&quot; /&gt;
        ///    &lt;namespace id=&quot;0x6&quot; startIndex=&quot;0xC05&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHalo3Strings {
            get {
                return ResourceManager.GetString("MccHalo3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;VertexDefinitions&gt;
        ///  &lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_4&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x10&quot; type=&quot;Float16_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;Int16_N4&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x1C&quot; type=&quot;Int16_N4&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///  &lt;/vertex&gt;
        ///  &lt;vertex type=&quot;0x01&quot; name=&quot;s_rigid_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHalo3VertexBuffer {
            get {
                return ResourceManager.GetString("MccHalo3VertexBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- https://github.com/XboxChaos/Assembly/tree/dev/src/Blamite/Formats --&gt;
        ///&lt;stringDefinitions&gt;
        ///  &lt;stringIDs id=&quot;U0&quot; indexBits=&quot;17&quot; namespaceBits=&quot;8&quot; lengthBits=&quot;7&quot;&gt;
        ///    &lt;namespace id=&quot;0x0&quot; min=&quot;0x4C9&quot; startIndex=&quot;0x173C&quot; /&gt;
        ///    &lt;namespace id=&quot;0x1&quot; startIndex=&quot;0x4C9&quot; /&gt;
        ///    &lt;namespace id=&quot;0x2&quot; startIndex=&quot;0xB2E&quot; /&gt;
        ///    &lt;namespace id=&quot;0x3&quot; startIndex=&quot;0xC07&quot; /&gt;
        ///    &lt;namespace id=&quot;0x4&quot; startIndex=&quot;0xC71&quot; /&gt;
        ///    &lt;namespace id=&quot;0x5&quot; startIndex=&quot;0xD4A&quot; /&gt;
        ///    &lt;namespace id=&quot;0x6&quot; startIndex=&quot;0xD70&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHaloReachStrings {
            get {
                return ResourceManager.GetString("MccHaloReachStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;VertexDefinitions&gt;
        ///  &lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_4&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x10&quot; type=&quot;Float16_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;Int16_N4&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x1C&quot; type=&quot;Int16_N4&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///  &lt;/vertex&gt;
        ///  &lt;vertex type=&quot;0x01&quot; name=&quot;s_rigid_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHaloReachVertexBuffer {
            get {
                return ResourceManager.GetString("MccHaloReachVertexBuffer", resourceCulture);
            }
        }
    }
}
