//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adjutant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adjutant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;classes&gt;
        ///  &lt;class code=&quot;actr&quot; name=&quot;actor&quot; /&gt;
        ///  &lt;class code=&quot;actv&quot; name=&quot;actor_variant&quot; /&gt;
        ///  &lt;class code=&quot;ant!&quot; name=&quot;antenna&quot; /&gt;
        ///  &lt;class code=&quot;antr&quot; name=&quot;model_animations&quot; /&gt;
        ///  &lt;class code=&quot;bipd&quot; name=&quot;biped&quot; /&gt;
        ///  &lt;class code=&quot;bitm&quot; name=&quot;bitmap&quot; /&gt;
        ///  &lt;class code=&quot;boom&quot; name=&quot;spheroid&quot; /&gt;
        ///  &lt;class code=&quot;cdmg&quot; name=&quot;continuous_damage_effect&quot; /&gt;
        ///  &lt;class code=&quot;coll&quot; name=&quot;model_collision_geometry&quot; /&gt;
        ///  &lt;class code=&quot;colo&quot; name=&quot;color_table&quot; /&gt;
        ///  &lt;class code=&quot;cont&quot; name=&quot;contrail&quot; /&gt;
        ///  &lt;class co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo1Classes {
            get {
                return ResourceManager.GetString("Halo1Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;classes&gt;
        ///  &lt;class code=&quot;*cen&quot; name=&quot;scenario_scenery_resource&quot; /&gt;
        ///  &lt;class code=&quot;*eap&quot; name=&quot;scenario_weapons_resource&quot; /&gt;
        ///  &lt;class code=&quot;*ehi&quot; name=&quot;scenario_vehicles_resource&quot; /&gt;
        ///  &lt;class code=&quot;*fsc&quot; name=&quot;scenario_effect_scenery_resource&quot; /&gt;
        ///  &lt;class code=&quot;*igh&quot; name=&quot;scenario_lights_resource&quot; /&gt;
        ///  &lt;class code=&quot;*ipd&quot; name=&quot;scenario_bipeds_resource&quot; /&gt;
        ///  &lt;class code=&quot;*qip&quot; name=&quot;scenario_equipment_resource&quot; /&gt;
        ///  &lt;class code=&quot;*rea&quot; name=&quot;scenario_creature_resource&quot; /&gt;
        ///  &lt;class code=&quot;*sce&quot; name=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo2Classes {
            get {
                return ResourceManager.GetString("Halo2Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;VertexDefinitions&gt;
        ///  &lt;vertex type=&quot;0x00&quot; name=&quot;s_world_vertex&quot;&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x0&quot; type=&quot;Float32_3&quot; usage=&quot;position&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0xC&quot; type=&quot;Float32_2&quot; usage=&quot;texcoords&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x14&quot; type=&quot;DHenN3&quot; usage=&quot;normal&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x18&quot; type=&quot;DHenN3&quot; usage=&quot;tangent&quot; usageIndex=&quot;0&quot; /&gt;
        ///    &lt;value stream=&quot;0&quot; offset=&quot;0x1C&quot; type=&quot;DHenN3&quot; usage=&quot;binormal&quot; usageIndex=&quot;0&quot; /&gt;
        ///  &lt;/vertex&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3VertexBuffer {
            get {
                return ResourceManager.GetString("Halo3VertexBuffer", resourceCulture);
            }
        }
    }
}
