// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Common;

    // cache_file
    [Table("cache_file", Schema = "main")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CacheFile
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"cache_id", Order = 0, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "Cache ID")]
        public long CacheId { get; set; } // cache_id (Primary key)
        [Column(@"file_name", Order = 1, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(512)]
        [StringLength(512)]
        [Display(Name = "File name")]
        public string FileName { get; set; } // file_name (length: 512)

        [Column(@"build_string", Order = 2, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(32)]
        [StringLength(32)]
        [Display(Name = "Build string")]
        public string BuildString { get; set; } // build_string (length: 32)

        [Column(@"cache_type", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Cache type")]
        public CacheType CacheType { get; set; } // cache_type

        [Column(@"priority", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Priority")]
        public int Priority { get; set; } // priority

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) CacheFile pointed by [string_index].[cache_id] (fk_string_index_0)
        /// </summary>
        public virtual StringIndex StringIndex { get; set; } // string_index.fk_string_index_0
        /// <summary>
        /// Parent (One-to-One) CacheFile pointed by [tag_index].[cache_id] (fk_tag_index_0)
        /// </summary>
        public virtual TagIndex TagIndex { get; set; } // tag_index.fk_tag_index_0

        public CacheFile()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
