// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Definitions;

    // cache_file
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CacheFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CacheFile>
    {
        public CacheFileConfiguration()
            : this("main")
        {
        }

        public CacheFileConfiguration(string schema)
        {
            Property(x => x.FileName).IsUnicode(false);
            Property(x => x.BuildString).IsUnicode(false);
        }
    }

}
// </auto-generated>
