// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Definitions;

    // path
    [Table("path", Schema = "main")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Path
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"path_id", Order = 0, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "Path ID")]
        public long PathId { get; set; } // path_id (Primary key)
        [Column(@"value", Order = 1, TypeName = "varchar")]
        [MaxLength(512)]
        [StringLength(512)]
        [Display(Name = "Value")]
        public string Value { get; set; } // value (length: 512)

        // Reverse navigation

        /// <summary>
        /// Child IndexItems where [index_item].[path_id] point to this entity (fk_index_item_0)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<IndexItem> IndexItems { get; set; } // index_item.fk_index_item_0

        public Path()
        {
            IndexItems = new System.Collections.Generic.List<IndexItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
