// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Common;

    // string_value
    [Table("string_value", Schema = "main")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class StringValue
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"value_id", Order = 0, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "Value ID")]
        public long ValueId { get; set; } // value_id (Primary key)
        [Column(@"value", Order = 1, TypeName = "varchar")]
        [MaxLength(512)]
        [StringLength(512)]
        [Display(Name = "Value")]
        public string Value { get; set; } // value (length: 512)

        // Reverse navigation

        /// <summary>
        /// Child StringItems where [string_item].[value_id] point to this entity (fk_string_item_0)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StringItem> StringItems { get; set; } // string_item.fk_string_item_0

        public StringValue()
        {
            StringItems = new System.Collections.Generic.List<StringItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
