// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Common;

    // string_item
    [Table("string_item", Schema = "main")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class StringItem
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"cache_id", Order = 0, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "Cache ID")]
        public long CacheId { get; set; } // cache_id (Primary key)
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"string_id", Order = 1, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "String ID")]
        public long StringId { get; set; } // string_id (Primary key)

        [Column(@"value_id", Order = 2, TypeName = "integer")]
        [Display(Name = "Value ID")]
        public long? ValueId { get; set; } // value_id

        // Foreign keys

        /// <summary>
        /// Parent StringIndex pointed by [string_item].([CacheId]) (fk_string_item_1)
        /// </summary>
        [ForeignKey("CacheId"), Required] public virtual StringIndex StringIndex { get; set; } // fk_string_item_1

        /// <summary>
        /// Parent StringValue pointed by [string_item].([ValueId]) (fk_string_item_0)
        /// </summary>
        [ForeignKey("ValueId")] public virtual StringValue StringValue { get; set; } // fk_string_item_0

        public StringItem()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
