// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Common;

    // string_index
    [Table("string_index", Schema = "main")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class StringIndex
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"cache_id", Order = 0, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "Cache ID")]
        [ForeignKey("CacheFile")]
        public long CacheId { get; set; } // cache_id (Primary key)
        [Column(@"string_count", Order = 1, TypeName = "int")]
        [Required]
        [Display(Name = "String count")]
        public int StringCount { get; set; } // string_count

        // Reverse navigation

        /// <summary>
        /// Child StringItems where [string_item].[cache_id] point to this entity (fk_string_item_1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StringItem> StringItems { get; set; } // string_item.fk_string_item_1

        // Foreign keys

        /// <summary>
        /// Parent CacheFile pointed by [string_index].([CacheId]) (fk_string_index_0)
        /// </summary>
        [ForeignKey("CacheId"), Required] public virtual CacheFile CacheFile { get; set; } // fk_string_index_0

        public StringIndex()
        {
            StringItems = new System.Collections.Generic.List<StringItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
