// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reclaimer.Entities
{
    using Adjutant.Blam.Definitions;

    // tag_index
    [Table("tag_index", Schema = "main")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class TagIndex
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"cache_id", Order = 0, TypeName = "integer")]
        [Required]
        [Key]
        [Display(Name = "Cache ID")]
        [ForeignKey("CacheFile")]
        public long CacheId { get; set; } // cache_id (Primary key)
        [Column(@"magic", Order = 1, TypeName = "int")]
        [Required]
        [Display(Name = "Magic")]
        public int Magic { get; set; } // magic

        [Column(@"tag_count", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Tag count")]
        public int TagCount { get; set; } // tag_count

        // Reverse navigation

        /// <summary>
        /// Child TagItems where [tag_item].[cache_id] point to this entity (fk_tag_item_1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TagItem> TagItems { get; set; } // tag_item.fk_tag_item_1

        // Foreign keys

        /// <summary>
        /// Parent CacheFile pointed by [tag_index].([CacheId]) (fk_tag_index_0)
        /// </summary>
        [ForeignKey("CacheId"), Required] public virtual CacheFile CacheFile { get; set; } // fk_tag_index_0

        public TagIndex()
        {
            TagItems = new System.Collections.Generic.List<TagItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
